"""Downloads the Material Symbols icons the app uses into res/drawable as vector drawables.

Run from android/:  python tools/fetch_icons.py
Icons are Material Symbols Outlined (Apache License 2.0). Paths are filled dark ink; tint them in layouts.
"""
import pathlib
import re
import sys
import urllib.request

ICONS = {  # drawable name: (symbol, variant)
    "ic_settings": ("settings", "default"),
    "ic_backspace": ("backspace", "default"),
    "ic_ink_eraser": ("ink_eraser", "default"),
    "ic_volume_up": ("volume_up", "default"),
    "ic_warning": ("warning", "fill1"),
    "ic_no_photography": ("no_photography", "default"),
    "ic_info": ("info", "default"),
    "ic_check_circle": ("check_circle", "fill1"),
    "ic_error": ("error", "fill1"),
    "ic_history": ("history", "default"),
    "ic_deployed_code": ("deployed_code", "default"),
    "ic_sync": ("sync", "default"),
    "ic_chevron_right": ("chevron_right", "default"),
    "ic_expand_more": ("expand_more", "default"),
    "ic_expand_less": ("expand_less", "default"),
    "ic_cameraswitch": ("cameraswitch", "default"),
    "ic_back_hand": ("back_hand", "default"),
    "ic_flight": ("flight", "default"),
    "ic_arrow_back": ("arrow_back", "default"),
}
URL = "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/{}/24px.svg"
TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Material Symbols Outlined "{symbol}" ({variant}), Apache License 2.0. Generated by tools/fetch_icons.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960">
    <group android:translateY="960">
{paths}
    </group>
</vector>
"""

out = pathlib.Path(__file__).resolve().parent.parent / "app" / "src" / "main" / "res" / "drawable"
for name, (symbol, variant) in ICONS.items():
    svg = urllib.request.urlopen(URL.format(symbol, variant), timeout=30).read().decode("utf-8")
    ds = re.findall(r'<path[^>]*\sd="([^"]+)"', svg)
    if not ds:
        sys.exit(f"no <path> in {symbol}")
    paths = "\n".join(f'        <path android:fillColor="#FF111827" android:pathData="{d}" />' for d in ds)
    (out / f"{name}.xml").write_text(TEMPLATE.format(symbol=symbol, variant=variant, paths=paths), encoding="utf-8")
    print("wrote", name)
